name: Update IPTV Playlist

on:
  schedule:
    - cron: "0 2 * * *"   # раз в сутки (02:00 UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run crawler
        run: python crawler.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.m3u channels.json
          git commit -m "Update IPTV playlist" || echo "No changes"
          git push
