name: Update IPTV Playlist

on:
  schedule:
    - cron: "0 2 * * *"   
  workflow_dispatch:       

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run crawler
        run: python crawler.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add playlist.m3u channels.json

          
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update IPTV playlist [skip ci]"
            git push
          fi
